### ISSUE TITLE
Error： generate quantum circuit image with qutip

### ISSUE THREAD

**Issue by luopeis** [hodgestar/qutip-asqsqis-2022#4]
Dear friends of  the groups,

I had some trouble installing the qutip.
![first](https://user-images.githubusercontent.com/128964528/230753196-e09081d3-1c5a-41eb-ba16-102e69ffbd28.png)
![second](https://user-images.githubusercontent.com/128964528/230753197-b8034aa2-de8f-44e1-913b-fbd1b79572fa.png)

**Comment by hodgestar** [comment]
@luopeis Please don't post the same issue in many different places.
